SET search_path to lookups,public
--http://localhost/scripts/redshift/tools/studio.pl?source_connection=default&destination_connection=reports&source_database=public&destination_database=lookups&destination_tables=agent_headoffices&destination_tables=agent_tiers&destination_tables=bdms&destination_tables=hotel_chains&destination_tables=status&destination_tables=suppliers&destination_tables=tableau_additional&destination_tables=tableau_bookings&destination_tables=tableau_reference&destination_tables=tableau_sp&destination_tables=v_hotel_to_chain&Execute=Execute&subject=Tables&action=generate_view&.cgifields=subject&.cgifields=destination_tables&.cgifields=source_tables#
;
drop table if exists tableau_bookings_x
;
create table tableau_bookings_x as
select
"agent_headoffices"."id_headoffice" as "agent_headoffices_id_headoffice",
"agent_headoffices"."agent_headoffice" as "agent_headoffices_agent_headoffice",
"agent_headoffices"."agent_consortia" as "agent_headoffices_agent_consortia",
"agent_headoffices"."agent_count" as "agent_headoffices_agent_count",
"agent_headoffices"."net_price" as "agent_headoffices_net_price",

"agent_tiers"."id_agent" as "agent_tiers_id_agent",
"agent_tiers"."tier" as "agent_tiers_tier",
"agent_tiers"."agent_enabled" as "agent_tiers_agent_enabled",

"bdms"."email" as "bdms_email",
"bdms"."disabled" as "bdms_disabled",
"bdms"."market" as "bdms_market",
"bdms"."target" as "bdms_target",
"bdms"."target%" as "bdms_target%",
"bdms"."base" as "bdms_base",
"bdms"."global_market" as "bdms_global_market",

"hotel_chains"."id_chain" as "hotel_chains_id_chain",
"hotel_chains"."hotel_chain" as "hotel_chains_hotel_chain",
"hotel_chains"."hotel_brand" as "hotel_chains_hotel_brand",
"hotel_chains"."id_group" as "hotel_chains_id_group",
"hotel_chains"."hotel_group" as "hotel_chains_hotel_group",

"status"."id_item_status" as "status_id_item_status",
"status"."item_status_alias" as "status_item_status_alias",
"status"."item_status" as "status_item_status",
"status"."backoffice_name" as "status_backoffice_name",
"status"."status_backoffice" as "status_status_backoffice",
"status"."agents_name" as "status_agents_name",
"status"."status_agents" as "status_status_agents",
"status"."backoffice_cancelled" as "status_backoffice_cancelled",

"suppliers"."id_supplier" as "suppliers_id_supplier",
"suppliers"."supplier" as "suppliers_supplier",
"suppliers"."supplier_direct" as "suppliers_supplier_direct",
"suppliers"."supplier_postpre" as "suppliers_supplier_postpre",
"suppliers"."supplier_group" as "suppliers_supplier_group",
"suppliers"."activity" as "suppliers_activity",
"suppliers"."override%" as "suppliers_override%",

"tableau_additional"."id_booking" as "tableau_additional_id_booking",
"tableau_additional"."id_item" as "tableau_additional_id_item",
"tableau_additional"."item_type" as "tableau_additional_item_type",
"tableau_additional"."agency_reference_number" as "tableau_additional_agency_reference_number",

"tableau_bookings"."id_tableau_item" as "tableau_bookings_id_tableau_item",
"tableau_bookings"."item_type" as "tableau_bookings_item_type",
"tableau_bookings"."id_item" as "tableau_bookings_id_item",
"tableau_bookings"."id_booking" as "tableau_bookings_id_booking",
"tableau_bookings"."id_supplier" as "tableau_bookings_id_supplier",
"tableau_bookings"."is_packaged_rate" as "tableau_bookings_is_packaged_rate",
"tableau_bookings"."id_source" as "tableau_bookings_id_source",
"tableau_bookings"."id_user" as "tableau_bookings_id_user",
"tableau_bookings"."id_agent" as "tableau_bookings_id_agent",
"tableau_bookings"."supplier" as "tableau_bookings_supplier",
"tableau_bookings"."takeoff_contract" as "tableau_bookings_takeoff_contract",
"tableau_bookings"."item_name" as "tableau_bookings_item_name",
"tableau_bookings"."arrival" as "tableau_bookings_arrival",
"tableau_bookings"."departure" as "tableau_bookings_departure",
"tableau_bookings"."product" as "tableau_bookings_product",
"tableau_bookings"."product_subproduct" as "tableau_bookings_product_subproduct",
"tableau_bookings"."id_item_status" as "tableau_bookings_id_item_status",
"tableau_bookings"."is_booked_by_po" as "tableau_bookings_is_booked_by_po",
"tableau_bookings"."is_cancelled_by_po" as "tableau_bookings_is_cancelled_by_po",
"tableau_bookings"."is_paid_unavailable" as "tableau_bookings_is_paid_unavailable",
"tableau_bookings"."item_status" as "tableau_bookings_item_status",
"tableau_bookings"."item_statusalias" as "tableau_bookings_item_statusalias",
"tableau_bookings"."id_client" as "tableau_bookings_id_client",
"tableau_bookings"."id_client_type" as "tableau_bookings_id_client_type",
"tableau_bookings"."id_client_ab" as "tableau_bookings_id_client_ab",
"tableau_bookings"."client_type" as "tableau_bookings_client_type",
"tableau_bookings"."agent" as "tableau_bookings_agent",
"tableau_bookings"."agent_postal_code" as "tableau_bookings_agent_postal_code",
"tableau_bookings"."id_headoffice" as "tableau_bookings_id_headoffice",
"tableau_bookings"."agent_headoffice" as "tableau_bookings_agent_headoffice",
"tableau_bookings"."agent_region" as "tableau_bookings_agent_region",
"tableau_bookings"."agent_country" as "tableau_bookings_agent_country",
"tableau_bookings"."agent_state" as "tableau_bookings_agent_state",
"tableau_bookings"."agent_city" as "tableau_bookings_agent_city",
"tableau_bookings"."agent_citydistrict" as "tableau_bookings_agent_citydistrict",
"tableau_bookings"."agent_user" as "tableau_bookings_agent_user",
"tableau_bookings"."is_preferred_agent" as "tableau_bookings_is_preferred_agent",
"tableau_bookings"."id_hotel" as "tableau_bookings_id_hotel",
"tableau_bookings"."stars" as "tableau_bookings_stars",
"tableau_bookings"."hotel_chain" as "tableau_bookings_hotel_chain",
"tableau_bookings"."room_description" as "tableau_bookings_room_description",
"tableau_bookings"."account_owner" as "tableau_bookings_account_owner",
"tableau_bookings"."email" as "tableau_bookings_email",
"tableau_bookings"."region" as "tableau_bookings_region",
"tableau_bookings"."country" as "tableau_bookings_country",
"tableau_bookings"."state" as "tableau_bookings_state",
"tableau_bookings"."city" as "tableau_bookings_city",
"tableau_bookings"."citydistrict" as "tableau_bookings_citydistrict",
"tableau_bookings"."agent_sales_area" as "tableau_bookings_agent_sales_area",
"tableau_bookings"."lat" as "tableau_bookings_lat",
"tableau_bookings"."lon" as "tableau_bookings_lon",
"tableau_bookings"."cancelled_date" as "tableau_bookings_cancelled_date",
"tableau_bookings"."paid_date" as "tableau_bookings_paid_date",
"tableau_bookings"."confirmed_date" as "tableau_bookings_confirmed_date",
"tableau_bookings"."payment_due_date" as "tableau_bookings_payment_due_date",
"tableau_bookings"."instant_purchase_date" as "tableau_bookings_instant_purchase_date",
"tableau_bookings"."supplier_paid_date" as "tableau_bookings_supplier_paid_date",
"tableau_bookings"."rewards_promotion" as "tableau_bookings_rewards_promotion",
"tableau_bookings"."buy_price" as "tableau_bookings_buy_price",
"tableau_bookings"."buy_currency" as "tableau_bookings_buy_currency",
"tableau_bookings"."supplier_price" as "tableau_bookings_supplier_price",
"tableau_bookings"."supplier_currency" as "tableau_bookings_supplier_currency",
"tableau_bookings"."net_price" as "tableau_bookings_net_price",
"tableau_bookings"."net_currency" as "tableau_bookings_net_currency",
"tableau_bookings"."commission_price" as "tableau_bookings_commission_price",
"tableau_bookings"."commission_currency" as "tableau_bookings_commission_currency",
"tableau_bookings"."gross_price" as "tableau_bookings_gross_price",
"tableau_bookings"."gross_currency" as "tableau_bookings_gross_currency",
"tableau_bookings"."intelirates" as "tableau_bookings_intelirates",
"tableau_bookings"."cancellation_policy" as "tableau_bookings_cancellation_policy",
"tableau_bookings"."ap_markup" as "tableau_bookings_ap_markup",
"tableau_bookings"."ap_email_sent" as "tableau_bookings_ap_email_sent",
"tableau_bookings"."ap_qualified" as "tableau_bookings_ap_qualified",
"tableau_bookings"."ap_expired" as "tableau_bookings_ap_expired",
"tableau_bookings"."created" as "tableau_bookings_created",
"tableau_bookings"."modified" as "tableau_bookings_modified",
"tableau_bookings"."deleted" as "tableau_bookings_deleted",
"tableau_bookings"."fy2015_category" as "tableau_bookings_fy2015_category",
"tableau_bookings"."fy2015_subcategory" as "tableau_bookings_fy2015_subcategory",
"tableau_bookings"."fy2015_value_paid" as "tableau_bookings_fy2015_value_paid",
"tableau_bookings"."fy2015_number_paid" as "tableau_bookings_fy2015_number_paid",
"tableau_bookings"."hot_deal" as "tableau_bookings_hot_deal",

"tableau_reference"."item_type" as "tableau_reference_item_type",
"tableau_reference"."id_item" as "tableau_reference_id_item",
"tableau_reference"."product" as "tableau_reference_product",
"tableau_reference"."ref" as "tableau_reference_ref",
"tableau_reference"."location_name" as "tableau_reference_location_name",
"tableau_reference"."location_coordinates" as "tableau_reference_location_coordinates",
"tableau_reference"."lat" as "tableau_reference_lat",
"tableau_reference"."lon" as "tableau_reference_lon",
"tableau_reference"."country" as "tableau_reference_country",
"tableau_reference"."country_code" as "tableau_reference_country_code",
"tableau_reference"."id_hotel" as "tableau_reference_id_hotel",
"tableau_reference"."id_external" as "tableau_reference_id_external",
"tableau_reference"."name" as "tableau_reference_name",
"tableau_reference"."address" as "tableau_reference_address",
"tableau_reference"."city" as "tableau_reference_city",
"tableau_reference"."state" as "tableau_reference_state",
"tableau_reference"."postcode" as "tableau_reference_postcode",
"tableau_reference"."telephone" as "tableau_reference_telephone",
"tableau_reference"."fax" as "tableau_reference_fax",
"tableau_reference"."giata_id" as "tableau_reference_giata_id",
"tableau_reference"."created" as "tableau_reference_created",
"tableau_reference"."modified" as "tableau_reference_modified",
"tableau_reference"."deleted" as "tableau_reference_deleted",

"tableau_sp"."id_booking" as "tableau_sp_id_booking",
"tableau_sp"."id_item" as "tableau_sp_id_item",
"tableau_sp"."item_type" as "tableau_sp_item_type",
"tableau_sp"."adults" as "tableau_sp_adults",
"tableau_sp"."children" as "tableau_sp_children",
"tableau_sp"."has_children" as "tableau_sp_has_children",
"tableau_sp"."pax_names" as "tableau_sp_pax_names",
"tableau_sp"."child_ages" as "tableau_sp_child_ages",
"tableau_sp"."pax" as "tableau_sp_pax",

"v_hotel_to_chain"."id_hotel" as "v_hotel_to_chain_id_hotel",
"v_hotel_to_chain"."id_chain" as "v_hotel_to_chain_id_chain"

from public.tableau_bookings
left join agent_headoffices using(id_headoffice)
left join agent_tiers using(id_agent)
left join bdms using(email)
left join status using(id_item_status)
left join suppliers using(id_supplier)
left join tableau_sp using(id_item)
left join tableau_additional using(id_item)
left join tableau_reference using (id_item)
left join v_hotel_to_chain on tableau_bookings.id_hotel = v_hotel_to_chain.id_hotel
left join hotel_chains on v_hotel_to_chain.id_chain = hotel_chains.id_chain
